.\"
.\"  Copyright 1993,1998,2014 Toyoda Masashi (mtoyoda@acm.org)
.\"
.\"	@(#)sl.1
.\"
.TH SL 1 "March 31, 2014"
.SH NAME
sl \- cure your bad habit of mistyping. Patched long version (made customizable!)
.SH SYNOPSIS
.B sl
[
.B \-alFcCrRedDGh
]
[
.B -L\fINUM\fB
]
[
.B -C\fINUM\fB
]
[
.B -W\fINUM\fB
]
.SH DESCRIPTION
.B sl
is a highly advanced animation program for curing your bad habit of mistyping.
.PP
.TP
.B \-a
An accident is occurring. People cry for help.
.TP
.B \-l
Little version.
.TP
.B \-F
It flies like the galaxy express 999.
.TP
.B \-c
C51 appears instead of D51.
.TP
.B \-C
A gated level cross appears.
.TP
.B \-r
A fabulous rainbow appears on the animation!
.TP
.B \-R
The train will turn back in the other direction!
.TP
.B \-e
Evil mode: will not break for any signals!
.TP
.B \-d
People will dance on the roof (unless there is an accident)!
.TP
.B \-D
Disco mode. Alternate colors during animation.
.TP
.B \-G
It's French like Oscar.
.TP
.B \-h
Show a train with 3 locomotives, between 10 and 30 passenger cars, a gated level cross and possible return (identical with \fBsl-h\fR from debian).
.TP
.B \-L\fINUM\fB
Show \fINUM\fR locomotives (defaults to 1).
.TP
.B \-N\fINUM\fB
Show a train with \fINUM\fR passenger cars, the double value in little mode (defaults to 2 cars in little mode, 1 in French mode and 0 otherwise).
.TP
.B \-W\fINUM\fB
Sleep for \fINUM\fR milliseconds (defaults to a random number between 5 and 40).
.PP
.SH SEE ALSO
.BR ls (1)
.SH BUGS
It sometimes lists directory contents.
.SH AUTHOR
Toyoda Masashi (mtoyoda@acm.org)
